In [3]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (7.34.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (4.14.1)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.2.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.81.1)
Requirement already satisfied: keras>=3.12.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.14.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.2.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.8.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\adiba\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow import keras  #keras tensorflow ka use krke neural network banata hai
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [7]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [8]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [9]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [14]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [15]:
# DL ME HUM NORMALIZATION ZYADA USE KRTE HAIN RATHER THAN STANDARDIZATION JO ML me zyada use hota

In [16]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [17]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [18]:
 X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42, stratify =y)

In [21]:
model=keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [23]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
#NEURALNETWORKS WORK WITH ARRAYS NOT DATAFRAMES

In [26]:
#ab hum model ko fit karenge toh sabse phle fit krne ke train values denge 
#Aur phir validation ke liye test values dete hain aur hum .values de rhe kyuki it accepts only array no data frame
#then humare epochs decide kre jo FP and BP krta hai n times
#Then batch size btata hai ek ssath kitna dataa utha ke kaam krega ek ek krke karenge toh time zyada lagega
#verbose define krta hai training details ko show krna, agar 0 kro toh voh details nhi dikhayega ki at each epochs kya values rhin  but 1 krke saari details milti hain

In [24]:
histroy=model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=4,verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 231ms/step - accuracy: 0.5000 - loss: 0.7410 - val_accuracy: 0.5000 - val_loss: 0.7472
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7403 - val_accuracy: 0.5000 - val_loss: 0.7463
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7391 - val_accuracy: 0.5000 - val_loss: 0.7454
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7373 - val_accuracy: 0.5000 - val_loss: 0.7445
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7359 - val_accuracy: 0.5000 - val_loss: 0.7436
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7364 - val_accuracy: 0.5000 - val_loss: 0.7427
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7344 - val_accuracy: 0.5000 - val_loss: 0.7418
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7340 - val_accuracy: 0.5000 - val_loss: 0.7409
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7319 - val_accuracy: 0.5000 - val_loss: 0.7400
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7317 - val_accuracy: 0.5000 - val_loss: 0.7392
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7297 - val_accuracy: 0.5000 - val_loss: 0.7383
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7288 - val_accuracy: 0.5000 - val_loss: 0.7376
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7274 - val_accuracy: 0.5000 - val_loss: 0.7370
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7265 - val_accuracy: 0.5000 - val_loss: 0.7364
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5000 - loss: 0.7277 - val_accuracy: 0.5000 - val_loss: 0.7359
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.7246 - val_accuracy: 0.5000 - val_loss: 0.7353
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7238 - val_accuracy: 0.5000 - val_loss: 0.7348
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7236 - val_accuracy: 0.5000 - val_loss: 0.7342
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7227 - val_accuracy: 0.5000 - val_loss: 0.7337
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7225 - val_accuracy: 0.5000 - val_loss: 0.7331
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7216 - val_accuracy: 0.2500 - val_loss: 0.7326
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7207 - val_accuracy: 0.2500 - val_loss: 0.7320
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7200 - val_accuracy: 0.2500 - val_loss: 0.7315
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7193 - val_accuracy: 0.2500 - val_loss: 0.7308
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7179 - val_accuracy: 0.2500 - val_loss: 0.7301
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7174 - val_accuracy: 0.2500 - val_loss: 0.7294
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7169 - val_accuracy: 0.2500 - val_loss: 0.7287
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7171 - val_accuracy: 0.2500 - val_loss: 0.7280
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7154 - val_accuracy: 0.2500 - val_loss: 0.7274
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7138 - val_accuracy: 0.2500 - val_loss: 0.7268
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7135 - val_accuracy: 0.2500 - val_loss: 0.7261
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7132 - val_accuracy: 0.2500 - val_loss: 0.7253
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7132 - val_accuracy: 0.2500 - val_loss: 0.7245
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7107 - val_accuracy: 0.2500 - val_loss: 0.7237
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7107 - val_accuracy: 0.2500 - val_loss: 0.7228
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7094 - val_accuracy: 0.2500 - val_loss: 0.7220
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7088 - val_accuracy: 0.2500 - val_loss: 0.7213
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7084 - val_accuracy: 0.2500 - val_loss: 0.7206
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7084 - val_accuracy: 0.2500 - val_loss: 0.7199
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7066 - val_accuracy: 0.2500 - val_loss: 0.7193
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7065 - val_accuracy: 0.2500 - val_loss: 0.7187
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.7059 - val_accuracy: 0.2500 - val_loss: 0.7181
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7068 - val_accuracy: 0.2500 - val_loss: 0.7175
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7039 - val_accuracy: 0.2500 - val_loss: 0.7169
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7037 - val_accuracy: 0.2500 - val_loss: 0.7164
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.7027 - val_accuracy: 0.2500 - val_loss: 0.7158
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.7021 - val_accuracy: 0.2500 - val_loss: 0.7153
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.7024 - val_accuracy: 0.2500 - val_loss: 0.7147
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7009 - val_accuracy: 0.2500 - val_loss: 0.7142
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7008 - val_accuracy: 0.2500 - val_loss: 0.7136
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7005 - val_accuracy: 0.2500 - val_loss: 0.7130
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7008 - val_accuracy: 0.2500 - val_loss: 0.7125
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6987 - val_accuracy: 0.2500 - val_loss: 0.7118
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5833 - loss: 0.6992 - val_accuracy: 0.2500 - val_loss: 0.7112
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6972 - val_accuracy: 0.2500 - val_loss: 0.7106
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6970 - val_accuracy: 0.2500 - val_loss: 0.7099
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6985 - val_accuracy: 0.2500 - val_loss: 0.7093
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6958 - val_accuracy: 0.2500 - val_loss: 0.7086
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6955 - val_accuracy: 0.5000 - val_loss: 0.7080
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.6949 - val_accuracy: 0.5000 - val_loss: 0.7074
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6944 - val_accuracy: 0.5000 - val_loss: 0.7067
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5833 - loss: 0.6951 - val_accuracy: 0.5000 - val_loss: 0.7061
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.6941 - val_accuracy: 0.5000 - val_loss: 0.7054
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.6935 - val_accuracy: 0.5000 - val_loss: 0.7048
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5833 - loss: 0.6919 - val_accuracy: 0.5000 - val_loss: 0.7041
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - loss: 0.6913 - val_accuracy: 0.5000 - val_loss: 0.7035
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6910 - val_accuracy: 0.5000 - val_loss: 0.7029
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - loss: 0.6897 - val_accuracy: 0.5000 - val_loss: 0.7023
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5833 - loss: 0.6897 - val_accuracy: 0.5000 - val_loss: 0.7017
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.6889 - val_accuracy: 0.5000 - val_loss: 0.7012
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.6895 - val_accuracy: 0.5000 - val_loss: 0.7006
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5833 - loss: 0.6877 - val_accuracy: 0.5000 - val_loss: 0.7000
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.6871 - val_accuracy: 0.5000 - val_loss: 0.6994
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5833 - loss: 0.6863 - val_accuracy: 0.5000 - val_loss: 0.6988
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.6858 - val_accuracy: 0.5000 - val_loss: 0.6983
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6855 - val_accuracy: 0.5000 - val_loss: 0.6977
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6845 - val_accuracy: 0.5000 - val_loss: 0.6972
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.6839 - val_accuracy: 0.5000 - val_loss: 0.6966
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - loss: 0.6837 - val_accuracy: 0.5000 - val_loss: 0.6960
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.6828 - val_accuracy: 0.5000 - val_loss: 0.6955
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5833 - loss: 0.6832 - val_accuracy: 0.5000 - val_loss: 0.6949
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6821 - val_accuracy: 0.5000 - val_loss: 0.6943
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5833 - loss: 0.6811 - val_accuracy: 0.5000 - val_loss: 0.6938
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5833 - loss: 0.6809 - val_accuracy: 0.5000 - val_loss: 0.6930
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.6802 - val_accuracy: 0.5000 - val_loss: 0.6923
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5833 - loss: 0.6794 - val_accuracy: 0.5000 - val_loss: 0.6915
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.6789 - val_accuracy: 0.5000 - val_loss: 0.6907
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5833 - loss: 0.6780 - val_accuracy: 0.5000 - val_loss: 0.6901
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - loss: 0.6774 - val_accuracy: 0.5000 - val_loss: 0.6894
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - loss: 0.6765 - val_accuracy: 0.5000 - val_loss: 0.6888
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5833 - loss: 0.6762 - val_accuracy: 0.5000 - val_loss: 0.6882
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6753 - val_accuracy: 0.5000 - val_loss: 0.6875
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5833 - loss: 0.6750 - val_accuracy: 0.5000 - val_loss: 0.6869
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.6745 - val_accuracy: 0.5000 - val_loss: 0.6863
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6736 - val_accuracy: 0.5000 - val_loss: 0.6858
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6736 - val_accuracy: 0.5000 - val_loss: 0.6852
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6667 - loss: 0.6724 - val_accuracy: 0.5000 - val_loss: 0.6847
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.6667 - loss: 0.6740 - val_accuracy: 0.5000 - val_loss: 0.6842
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6667 - loss: 0.6719 - val_accuracy: 0.5000 - val_loss: 0.6838
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6667 - loss: 0.6714 - val_accuracy: 0.5000 - val_loss: 0.6834